/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: ["./index.html", "./src/**/*.{js,jsx}"],
  theme: {
    extend: {
      colors: {
        error: "#ffb4ab",
        "surface-container-high": "#2a2a2a",
        outline: "#8e9379",
        surface: "#131313",
        "on-primary-container": "#556d00",
        "primary-container": "#c3f400",
        primary: "#ffffff",
        "primary-fixed-dim": "#abd600",
        "inverse-surface": "#e5e2e1",
        "tertiary-container": "#ffdad5",
        "on-error": "#690005",
        "secondary-fixed-dim": "#00dbe9",
        "on-surface": "#e5e2e1",
        "inverse-primary": "#506600",
        "on-surface-variant": "#c4c9ac",
        "surface-container-lowest": "#0e0e0e",
        "tertiary-fixed": "#ffdad5",
        "on-error-container": "#ffdad6",
        tertiary: "#ffffff",
        "surface-variant": "#353534",
        "secondary-fixed": "#7df4ff",
        "outline-variant": "#444933",
        "on-secondary": "#00363a",
        "on-primary": "#283500",
        "inverse-on-surface": "#313030",
        "on-tertiary-container": "#ca0a0f",
        "on-secondary-fixed-variant": "#004f54",
        "surface-container": "#201f1f",
        "surface-bright": "#393939",
        background: "#131313",
        "surface-dim": "#131313",
        "surface-tint": "#abd600",
        "error-container": "#93000a",
        secondary: "#d3fbff",
        "surface-container-low": "#1c1b1b",
        "primary-fixed": "#c3f400",
        "secondary-container": "#00eefc",
        "on-secondary-fixed": "#002022",
        "on-tertiary": "#690003",
        "on-tertiary-fixed": "#410001",
        "surface-container-highest": "#353534",
        "on-primary-fixed-variant": "#3c4d00",
        "on-background": "#e5e2e1",
        "tertiary-fixed-dim": "#ffb4aa",
        "on-secondary-container": "#00686f",
        "on-primary-fixed": "#161e00",
        "on-tertiary-fixed-variant": "#930005",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      spacing: {
        base: "8px",
        lg: "40px",
        gutter: "16px",
        xs: "4px",
        sm: "12px",
        md: "24px",
        "margin-safe": "24px",
        xl: "64px",
      },
      fontFamily: {
        "label-bold": ["Inter"],
        "body-md": ["Inter"],
        "headline-lg": ["Lexend"],
        "stats-display": ["Lexend"],
        "headline-md": ["Lexend"],
        "body-lg": ["Inter"],
        "headline-xl": ["Lexend"],
      },
      fontSize: {
        "label-bold": ["14px", { lineHeight: "1", letterSpacing: "0.05em", fontWeight: "700" }],
        "body-md": ["16px", { lineHeight: "1.5", fontWeight: "400" }],
        "headline-lg": ["32px", { lineHeight: "1.2", letterSpacing: "-0.01em", fontWeight: "700" }],
        "stats-display": ["20px", { lineHeight: "1", fontWeight: "600" }],
        "headline-md": ["24px", { lineHeight: "1.2", fontWeight: "700" }],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
        "headline-xl": ["48px", { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "800" }],
      },
    },
  },
  plugins: [],
};
